[Eth]
NetworkId = 123
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 30000000
GasCeil = 40000000
GasPrice = 1000000000
Recommit = 10000000000
Noverify = false

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60


[Node]
DataDir = "node1"
InsecureUnlockAllowed = true
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "localhost"
HTTPPort = 8575
HTTPCors = ["*"]
HTTPVirtualHosts = ["*"]
HTTPModules = ["debug","eth", "net", "web3", "txpool", "admin"]
WSPort = 8576
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = true
StaticNodes = []

TrustedNodes = []

EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

